name: cifar-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow
      - torch
      - torchvision
      - pillow
      - tqdm
      - jupyterlab
      - scikit-learn
      - matplotlib
